# Generated by Django 5.1.8 on 2026-08-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('meter_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_open_id', models.CharField(blank=True, max_length=128)),
                ('voltage_v', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('current_a', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('power_w', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('balance_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('relay_status', models.CharField(default='ON', max_length=16)),
                ('signal_gsm', models.IntegerField(default=0)),
                ('device_status', models.CharField(default='OFFLINE', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('territory', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('warning_percentage', models.PositiveSmallIntegerField(default=80)),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='energy.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='energy.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('APP_PAIEMENT', 'APP_PAIEMENT'), ('SAISIE_MANUELLE', 'SAISIE_MANUELLE')], max_length=32)),
                ('energy_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('applied_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='energy.meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='energy.sector'),
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('applied_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('voltage_v', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_a', models.DecimalField(decimal_places=3, max_digits=10)),
                ('power_w', models.DecimalField(decimal_places=3, max_digits=12)),
                ('energy_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('relay_status', models.CharField(max_length=16)),
                ('signal_gsm', models.IntegerField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='energy.meter')),
            ],
        ),
    ]
