# Generated by Django 5.1.8 on 2026-08-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_seed_alfajiri_demo_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='meter',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='meter',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recharge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPLIED', 'APPLIED'), ('FAILED', 'FAILED')], default='APPLIED', max_length=16),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManualToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, unique=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('energy_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('issued_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_tokens', to='energy.meter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('meter', 'sequence'), name='uniq_manual_token_meter_sequence')],
            },
        ),
    ]
