# Generated by Django 5.1.8 on 2026-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_paymentevent_alter_alert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='subscriber_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meter',
            name='subscriber_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='meter',
            name='subscriber_phone',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
